# -*- coding: utf-8 -*-
"""weather-app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1148SatPuhq6EuxUI9BK24OKNbbpk1-bX
"""

import requests

def get_weather(city, api_key):
    base_url = "http://api.openweathermap.org/data/2.5/weather"
    params = {
        "q": city,
        "appid": api_key,
        "units": "metric"
    }

    response = requests.get(base_url, params=params)
    data = response.json()

    if response.status_code == 200:
        print(f"\nWeather in {data['name']}:")
        print(f"Temperature: {data['main']['temp']}°C")
        print(f"Humidity: {data['main']['humidity']}%")
        print(f"Condition: {data['weather'][0]['description'].capitalize()}")
    else:
        print("\nCity not found. Try again!")

# Replace with your API key
API_KEY = "37957664d995ac97bffd53f7323b77f5"

city = input("Enter city name: ")
get_weather(city, API_KEY)

